---
components:
  schemas: 
    TrafficFlowObserved: 
      $ref: "https://filipe-b-lopes-alb.github.io/dataModel.Transportation/TrafficFlowObserved/model.yaml#/TrafficFlowObserved"

    properties:
      endNode:
        description: "Street/Local where the traffic observation has ended"
        type: string
        x-ngsi:
          model: https://schema.org/Text
          type: Property
      delay:
        description: "Time delay in minutes the traffic has been generating"
        type: number
        x-ngsi:
          model: https://schema.org/Number
          type: Property
      level:
        description: "Level of severity of the traffic congestion"
        type: number
        x-ngsi:
          model: https://schema.org/Number
          type: Property
      length:
        description: "Length of the traffic registered"
        type: number
        x-ngsi:
          model: https://schema.org/Number
          type: Property

info:
  description:  |
    An observation of traffic flow conditions at a certain place and time.
  title: TrafficFlowObserved
  version: "0.0.1"
openapi: "3.0.0"

paths: 
  /ngsi-ld/v1/entities: 
    get: 
      description: "Retrieve a set of entities which matches a specific query from an NGSI-LD system"
      parameters: 
        - 
          in: query
          name: type
          required: true
          schema: 
            enum: 
              - TrafficFlowObserved
            type: string
      responses: 
        ? "200"
        : 
          content: 
            application/ld+json: 
              examples: 
                keyvalues: 
                  summary: "Key-Values Pairs"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.Transportation/TrafficFlowObserved/examples/example.json"
                normalized: 
                  summary: "Normalized NGSI-LD"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.Transportation/TrafficFlowObserved/examples/example-normalized.jsonld"
          description: OK
      tags: 
        - ngsi-ld
tags: 
  - 
    description: "NGSI-LD Linked-data Format"
    name: ngsi-ld
