---
components:
  schemas: 
    AirQualityObserved:
      type: object
      description: |
        This entity contains a description of a air quality observation over time. This entity is associated with the vertical segments of  smart cities and related IoT applications.
        This data model has been partially developed based on the "AirQualityObserved" data model available on the SmartDataModels database which has been developed with mobile operators and the GSMA.
        It is an extension of the data model and introduces the following changes:
        
        - The required field `location` is no longer considered required.
        
        - `pm5` is an additional field added.
        
        - `pm7` is an additional field added.
        
        - `particulesMass` is an additional field added.
        
        ## Data Model
        For a full description of the following attributes refer to GSMA [IoT Big Data Harmonised Data Model](https://github.com/GSMADeveloper/NGSI-LD-Entities) AirQualityObserved Entity.
    
      allOf:
        - $ref: "https://filipe-b-lopes-alb.github.io/dataModel.Environment/AirQualityObserved/model.yaml#/AirQualityObserved"

      properties:
        pm7:
          x-ngsi:
            model: 'https://schema.org/Number'
            type: "Property"
          type: number
          format: float
          description: "Particulate matter 7.0 micrometers or less in diameter"
        pm5:
          x-ngsi:
            model: 'https://schema.org/Number'
            type: "Property"
          type: number
          format: float
          description: "Particulate matter 5.0 micrometers or less in diameter"
        particulesMass:
          x-ngsi:
            model: 'https://schema.org/Number'
            type: "Property"
          type: number
          format: float
          description: ""

info:
  description: |
    An extended observation of weather conditions at a certain place and time, based on the SmartDataModel AirQualityObserved
  title: AirQualityObserved
  version: "0.0.1"

openapi: "3.0.0"

paths: 
  /ngsi-ld/v1/entities: 
    get: 
      description: "Retrieve a set of entities which matches a specific query from an NGSI-LD system."
      parameters: 
        - 
          in: query
          name: type
          required: true
          schema: 
            enum: 
              - AirQualityObserved
            type: string
      responses: 
        "200":
          description: OK
          content: 
            application/ld+json: 
              examples: 
                keyvalues: 
                  summary: "Key-Values Pairs"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.Weather/AirQualityObserved/examples/example.json"
                normalized: 
                  summary: "Normalized NGSI-LD"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.Weather/AirQualityObserved/examples/example-normalized.jsonld"
      tags: 
        - ngsi-ld

tags: 
  - 
    description: "NGSI-LD Linked-data Format"
    name: ngsi-ld
