---
components:
  schemas: 
    NoiseLevelObserved:
      type: object
      description: |
        This entity contains a description of noise level observation over time. This entity is associated with the vertical segments of  smart cities and related IoT applications.
        This data model has been partially developed based on the "NoiseLevelObserved" data model available on the SmartDataModels database.
        It is an extension of the data model and introduces the following changes:
        
        - The required fields `dateObservedFrom` and `dateObservedTo` are no longer considered required but the field dateObserved is and this represent the datetime of the reading.
        
      allOf:
        - $ref: "https://filipe-b-lopes-alb.github.io/dataModel.Environment/NoiseLevelObserved/model.yaml#/NoiseLevelObserved"

info:
  description: |
    An extended observation of weather conditions at a certain place and time, based on the SmartDataModel NoiseLevelObserved
  title: NoiseLevelObserved
  version: "0.0.1"

openapi: "3.0.0"

paths: 
  /ngsi-ld/v1/entities: 
    get: 
      description: "Retrieve a set of entities which matches a specific query from an NGSI-LD system."
      parameters: 
        - 
          in: query
          name: type
          required: true
          schema: 
            enum: 
              - NoiseLevelObserved
            type: string
      responses: 
        "200":
          description: OK
          content: 
            application/ld+json: 
              examples: 
                keyvalues: 
                  summary: "Key-Values Pairs"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.Environment/NoiseLevelObserved/examples/example.json"
                normalized: 
                  summary: "Normalized NGSI-LD"
                  value: 
                    - 
                      $ref: "https://smart-data-models.github.io/dataModel.Environment/NoiseLevelObserved/examples/example-normalized.jsonld"
      tags: 
        - ngsi-ld

tags: 
  - 
    description: "NGSI-LD Linked-data Format"
    name: ngsi-ld
